# Generated by Django 4.2.1 on 2023-05-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='timestamp',
            new_name='timestamp_created',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
