# Generated by Django 4.2.1 on 2023-05-31 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_timestamp_task_timestamp_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='timestamp_created',
            new_name='timestamp',
        ),
    ]
